
VAR_GROUPS_SUPER_COMPACT = [
	'S7:[Collegamento_IM151_8]Status.Generale',
	'S7:[Collegamento_IM151_8]Gruppo1.Fase',
	'S7:[Collegamento_IM151_8]Gruppo1.Echo_Ingressi',
	'S7:[Collegamento_IM151_8]Gruppo1.Allarmi',
	'S7:[Collegamento_IM151_8]Gruppo2.Fase',
	'S7:[Collegamento_IM151_8]Gruppo2.Echo_Ingressi',
	'S7:[Collegamento_IM151_8]Gruppo2.Allarmi',
	'S7:[Collegamento_IM151_8]Gruppo3.Fase',
	'S7:[Collegamento_IM151_8]Gruppo3.Echo_Ingressi',
	'S7:[Collegamento_IM151_8]Gruppo3.Allarmi'
]


VARS_GENERALE= [
	('Status.Status.Modalita',               'db200_dbx0_0', 'bool', '0 = manuale ; 1 = automatico'),
	('Status.Stato_Ciclo_Automatico',        'db200_dbx0_1', 'bool', '0 = non attivo ; 1= in corso'),
	('Status.Status.Errore',                 'db200_dbx0_2', 'bool', '0= nessun errore; 1= errore presente'),
	('Status.Status.Gruppo1_Posizione_Base', 'db200_dbx0_3', 'bool', '1= gruppo in posizione base'),
	('Status.Status.Gruppo2_Posizione_Base', 'db200_dbx0_4', 'bool', '1= gruppo in posizione base'),
	('Status.Status.Gruppo3_Posizione_Base', 'db200_dbx0_5', 'bool', '1= gruppo in posizione base'),
]


VARS_GRUPPO_1_FASI = [
	('Status.Gruppo1.Passo_Auto_Sequenza[1]',  'db200_dbx42_0', 'bool', 'Fase Sollevamento Staffa su Giostra Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[2]',  'db200_dbx42_1', 'bool', 'Fase Bloccaggio Staffa sotto Pugno Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[3]',  'db200_dbx42_2', 'bool', 'Fase Traslatore Pugno -> Smottatura Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[4]',  'db200_dbx42_3', 'bool', 'Fase Abbassamento Pugno Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[5]',  'db200_dbx42_4', 'bool', 'Fase Alza Pugno Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[6]',  'db200_dbx42_5', 'bool', 'Fase Traslatore Pugno -> Linea Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[7]',  'db200_dbx42_6', 'bool', 'Fase Sbloccaggio Staffa Sotto Pugno Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[8]',  'db200_dbx42_7', 'bool', 'Fase Abbassa Sollevatore Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[9]',  'db200_dbx43_0', 'bool', 'Fase Fine Ciclo Smottatura Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[10]', 'db200_dbx43_1', 'bool', 'Fase Blocco Staffa sotto Disaccoppiatura Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[11]', 'db200_dbx43_2', 'bool', 'Fase Apri Pinza Disaccoppiatrice Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[12]', 'db200_dbx43_3', 'bool', 'Fase Abbassa Disaccoppiatrice Prelievo 1/2 Superiore Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[13]', 'db200_dbx43_4', 'bool', 'Fase Chiudi Pinza Disaccoppiatrice Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[14]', 'db200_dbx43_5', 'bool', 'Fase Alza Disaccoppiatrice Prelievo Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[15]', 'db200_dbx43_6', 'bool', 'Fase Sblocca Staffa sotto Disaccoppiatrice Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[16]', 'db200_dbx43_7', 'bool', 'Fase Apre Pinza Disaccoppiatrice Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[17]', 'db200_dbx44_0', 'bool', 'Fase Abbassa disaccoppiatrice Prelievo 1/2 Inferiore Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[18]', 'db200_dbx44_1', 'bool', 'Fase Chiude Pinza Disaccoppiatrice Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[19]', 'db200_dbx44_2', 'bool', 'Fase Alza Disaccoppiatore Prelievo 1/2 inferiore Attiva'),
	('Status.Gruppo1.Passo_Auto_Sequenza[20]', 'db200_dbx44_3', 'bool', 'Fase Fine Ciclo Gruppo 1 Attiva'),
]

VARS_GRUPPO_1_INGRESSI = [
	('Status.Gruppo1.Echo_Ingressi[1]',  'db200_dbx54_0', 'bool', '"SQ1700 Sollevatore Distaffatura Alto (E1.0)'),
	('Status.Gruppo1.Echo_Ingressi[2]',  'db200_dbx54_1', 'bool', '"SQ1701 Sollevatore Distaffatura Basso (E1.1)'),
	('Status.Gruppo1.Echo_Ingressi[3]',  'db200_dbx54_2', 'bool', '"PX1705 Traslazione Staffe in distaffatura Fuori (E1.5)'),
	('Status.Gruppo1.Echo_Ingressi[4]',  'db200_dbx54_3', 'bool', '"PX1704 Traslazione Staffe in distaffatura Rallentamento Fuori (E1.4)'),
	('Status.Gruppo1.Echo_Ingressi[5]',  'db200_dbx54_4', 'bool', '"PX1703 Traslazione Staffe in distaffatura Rallentamento Dentro (E1.3)'),
	('Status.Gruppo1.Echo_Ingressi[6]',  'db200_dbx54_5', 'bool', '"PX1702 Traslazione Staffe in distaffatura Dentro (E1.2)'),
	('Status.Gruppo1.Echo_Ingressi[7]',  'db200_dbx54_6', 'bool', '"PX1707 Pugno distaffatura basso (E1.7)'),
	('Status.Gruppo1.Echo_Ingressi[8]',  'db200_dbx54_7', 'bool', '"PX1706 Pugno distaffatura alto (E1.6)'),
	('Status.Gruppo1.Echo_Ingressi[9]',  'db200_dbx55_0', 'bool', '"PX16010 Bloccaggio distaffatura Staffa Bloccata (E2.0)'),
	('Status.Gruppo1.Echo_Ingressi[10]', 'db200_dbx55_1', 'bool', '"PX1611 Bloccaggio distaffatura Staffa Bloccata (E2.1)'),
	('Status.Gruppo1.Echo_Ingressi[11]', 'db200_dbx55_2', 'bool', '"SQ1804 Pinza Disaccoppiatura Aperta (E2.4)'),
	('Status.Gruppo1.Echo_Ingressi[12]', 'db200_dbx55_3', 'bool', '"SQ1805 Pinza Disaccoppiatura Chiusa (E2.5)'),
	('Status.Gruppo1.Echo_Ingressi[13]', 'db200_dbx55_4', 'bool', '"PX1902 Disaccoppiatore Staffe basso (E3.2)'),
	('Status.Gruppo1.Echo_Ingressi[14]', 'db200_dbx55_5', 'bool', '"PX1901 Disaccoppiatore Staffe rallentamento basso (E3.1)'),
	('Status.Gruppo1.Echo_Ingressi[15]', 'db200_dbx55_6', 'bool', '"PX1910 Disaccoppiatore Staffe in prelievo (E3.0)'),
	('Status.Gruppo1.Echo_Ingressi[16]', 'db200_dbx55_7', 'bool', '"PX1807 Disaccoppiatore Rallentamento (E2.7)'),
	('Status.Gruppo1.Echo_Ingressi[17]', 'db200_dbx56_0', 'bool', '"PX1806 Disaccoppiatore Alto (E2.6)'),
	('Status.Gruppo1.Echo_Ingressi[18]', 'db200_dbx56_1', 'bool', '"SQ1913 Bloccaggio Disaccoppiatura Bloccata (E3.3)'),
	('Status.Gruppo1.Echo_Ingressi[19]', 'db200_dbx56_2', 'bool', '"SQ1914 Bloccaggio Disaccoppiatura Sbloccata (E3.4)'),
]

VARS_GRUPPO_1_ALLARMI = [
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_0', 'bool', 'Timeout Gruppo 1 - Blocco Staffa sotto Disaccoppiatura - controllare  SQ1913 (Bloccaggio Distaffatura 1/2 Inferiore Bloccato)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_1', 'bool', 'Timeout Gruppo 1 - Apri Pinza Disaccoppiatrice - controllare  SQ1804 (Pinza Disaccoppiatura Aperta)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_2', 'bool', 'Timeout Gruppo 1 - Abbassa Disaccoppiatrice Prelievo 1/2 Superiore - controllare  PX1910 (Disaccoppiatura Staffe 1/2 Superiore in Prelievo)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_3', 'bool', 'Timeout Gruppo 1 - Chiudi Pinza Disaccoppiatrice - controllare  SQ1805 (Pinza Disaccoppiatura Chiusa)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_4', 'bool', 'Timeout Gruppo 1 - Alza Disaccoppiatrice Prelievo - controllare  PX1806 (Disaccoppiatore Alto)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_5', 'bool', 'Timeout Gruppo 1 - Sblocca Staffa sotto Disaccoppiatrice - controllare  SQ1914 (Bloccaggio Disaccoppiatura 1/2 Inferiore Sbloccata)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_6', 'bool', 'Timeout Gruppo 1 - Apre Pinza Disaccoppiatrice - controllare  SQ1804 (Pinza Disaccoppiatura Aperta)  '),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx58_7', 'bool', 'Timeout Gruppo 1 - Abbassa disaccoppiatrice Prelievo 1/2 Inferiore - controllare  PX1902 (Disaccoppiatore Staffe Basso Prelievo 1/2 Superiore) '),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_0', 'bool', 'Timeout Gruppo 1 - Sollevamento Staffa su Giostra - controllare SQ1700(Sollevatore Distaffatura Alto)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_1', 'bool', 'Timeout Gruppo 1 - Bloccaggio Staffa sotto Pugno - controllare  PX16010 (Bloccaggio Distaffatura)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_2', 'bool', 'Timeout Gruppo 1 - Traslatore Pugno -> Smottatura - controllare  PX1705 (Traslazione Staffe in Smottatura)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_3', 'bool', 'Timeout Gruppo 1 - Abbassamento Pugno - controllare  PX1707 (Pugno Distaffatura Basso)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_4', 'bool', 'Timeout Gruppo 1 - Alza Pugno - controllare  PX1706 (Pugno Distaffatura Alto)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_5', 'bool', 'Timeout Gruppo 1 - Traslatore Pugno -> Linea - controllare  PX1702 (Traslazione Staffe su Linea)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_6', 'bool', 'Timeout Gruppo 1 - Sbloccaggio Staffa Sotto Pugno - controllare  PX1611 (Staffa Bloccata)'),
	('Status.Gruppo1.Timeout[1]', 'db200_dbx59_7', 'bool', 'Timeout Gruppo 1 - Abbassa Sollevatore - controllare  SQ1701 (Sollevatore Distaffatura Basso)'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_0', 'bool', 'Gruppo 1 - Anomalia Sensori SQ1913/SQ1914 Bloccaggio Disaccoppiatura'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_1', 'bool', 'NONE'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_2', 'bool', 'NONE'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_3', 'bool', 'NONE'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_4', 'bool', 'NONE'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_5', 'bool', 'NONE'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_6', 'bool', 'NONE'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx60_7', 'bool', 'NONE'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_0', 'bool', 'Timeout Gruppo 1 - Chiude Pinza Disaccoppiatrice - controllare  SQ1805 (Pinza Disaccoppiatura Chiusa) '),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_1', 'bool', 'Timeout Gruppo 1 - Alza Disaccoppiatore Prelievo 1/2 inferiore - controllare  PX1806 (Disaccoppiatore Alto)'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_2', 'bool', 'Gruppo 1 - Anomalia Sensori SQ1700/SQ1701 Sollevatore Distaffatura'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_3', 'bool', 'Gruppo 1 - Anomalia Sensori PX1705/PX1702 Traslazione Staffe Distaffatura'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_4', 'bool', 'Gruppo 1 - Anomalia Sensori PX1707/PX1706 Pugno Distaffatura'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_5', 'bool', 'Gruppo 1 - Anomalia Sensori PX1610/PX1611 Bloccaggio Distaffatura'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_6', 'bool', 'Gruppo 1 - Anomalia Sensori SQ1804/SQ1805 Pinza Disaccoppiatura'),
	('Status.Gruppo1.Timeout[2]', 'db200_dbx61_7', 'bool', 'Gruppo 1 - Anomalia Sensori PX1902/PX1806 Disaccoppiatore Staffe'),
]


VARS_GRUPPO_2_FASI = [
	('Status.Gruppo2.Passo_Auto_Sequenza[1]',  'db200_dbx106_0', 'bool', 'Fase Sblocca Bloccaggi Linea Ramolaggio Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[2]',  'db200_dbx106_1', 'bool', 'Fase Uscita Spintore Ramolaggio Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[3]',  'db200_dbx106_2', 'bool', 'Fase Blocca Bloccaggi Linea Ramolaggio Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[4]',  'db200_dbx106_3', 'bool', 'Fase Entrata Spintore Ramolaggio Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[5]',  'db200_dbx106_4', 'bool', 'Fase Spintore Ramolaggio Inserito Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[6]',  'db200_dbx106_5', 'bool', 'Fase Sblocca Bloccaggio Transfer Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[7]',  'db200_dbx106_6', 'bool', 'Fase Ruota Transfer 1/2 Superiore Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[8]',  'db200_dbx106_7', 'bool', 'Fase Blocca Bloccaggio Transfer Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[9]',  'db200_dbx107_0', 'bool', 'Fase Salita Terra in carico Pressa Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[10]', 'db200_dbx107_1', 'bool', 'Fase Stop presa in carico Terra Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[11]', 'db200_dbx107_2', 'bool', 'Fase Apertura Tramoggia Terra Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[12]', 'db200_dbx107_3', 'bool', 'Fase Chiusura Tramoggia Terra Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[13]', 'db200_dbx107_4', 'bool', 'Fase Pressata 1/2 Superiore Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[14]', 'db200_dbx107_5', 'bool', 'Fase Stop Pressata 1/2 Superiore Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[15]', 'db200_dbx107_6', 'bool', 'Fase Discesa Pressa Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[16]', 'db200_dbx107_7', 'bool', 'Fase Pressa Bassa Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[17]', 'db200_dbx108_0', 'bool', 'Fase Start Ribaltatore Tutte Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[18]', 'db200_dbx108_1', 'bool', 'Fase Ribaltamento Tutte Manovra Eseguita Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[19]', 'db200_dbx108_2', 'bool', 'Fase Sblocca Bloccaggio Linea Ramolaggio Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[20]', 'db200_dbx108_3', 'bool', 'Fase Esce Spintore Ramolaggio *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[21]', 'db200_dbx108_4', 'bool', 'Fase Blocca Bloccaggi Linea Ramolaggio Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[22]', 'db200_dbx108_5', 'bool', 'Fase Entra Spintore ramolaggio *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[23]', 'db200_dbx108_6', 'bool', 'Fase Spintore Ramolaggio Dentro *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[24]', 'db200_dbx108_7', 'bool', 'Fase Sblocca bloccaggio Transfer *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[25]', 'db200_dbx109_0', 'bool', 'Fase Ruota Transfer 1/2 Superiore *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[26]', 'db200_dbx109_1', 'bool', 'Fase Blocca Bloccaggio Transfer *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[27]', 'db200_dbx109_2', 'bool', 'Fase Salita Pressa in Carico Terra *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[28]', 'db200_dbx109_3', 'bool', 'Fase Stop Pressa in Carico Terra *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[29]', 'db200_dbx109_4', 'bool', 'Fase Apertura Tramoggia Terra *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[30]', 'db200_dbx109_5', 'bool', 'Fase Chiusura Tramoggia Terra *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[31]', 'db200_dbx109_6', 'bool', 'Fase Pressata 1/2 Superiore *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[32]', 'db200_dbx109_7', 'bool', 'Fase Stop Pressata 1/2 Superiore *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[33]', 'db200_dbx110_0', 'bool', 'Fase Discesa Pressa *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[34]', 'db200_dbx110_1', 'bool', 'Fase Pressione Bassa *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[35]', 'db200_dbx110_2', 'bool', 'Fase Start Ribaltatore Tutte *II Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[36]', 'db200_dbx110_3', 'bool', 'Fase Start Ribaltatore Tutte Manovra Eseguita Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[37]', 'db200_dbx110_4', 'bool', 'Fase Salita Fresa Foro Colata Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[38]', 'db200_dbx110_5', 'bool', 'Fase Discesa Fresa Foro Colata Attiva'),
	('Status.Gruppo2.Passo_Auto_Sequenza[39]', 'db200_dbx110_6', 'bool', 'Fase Fine Ciclo Gruppo 2 Attiva'),
]

VARS_GRUPPO_2_INGRESSI = [
	('Status.Gruppo2.Echo_Ingressi[1]',  'db200_dbx118_0', 'bool', '"SQ2307 Bloccaggio prima della formatrice sbloccato (E7.7)'),
	('Status.Gruppo2.Echo_Ingressi[2]',  'db200_dbx118_1', 'bool', '"SQ2306 Bloccaggio prima della formatrice bloccato (E7.6)'),
	('Status.Gruppo2.Echo_Ingressi[3]',  'db200_dbx118_2', 'bool', '"PX2400 Spintore Formatrice Fuori (E8.0)'),
	('Status.Gruppo2.Echo_Ingressi[4]',  'db200_dbx118_3', 'bool', '"PX2401 Spintore Formatrice Dentro (E8.1)'),
	('Status.Gruppo2.Echo_Ingressi[5]',  'db200_dbx118_4', 'bool', '"PX2103 Contrasto Ramolaggio Rallentamento (E5.3)'),
	('Status.Gruppo2.Echo_Ingressi[6]',  'db200_dbx118_5', 'bool', '"PX2402 Transfer in posizione inferiore (E8.2)'),
	('Status.Gruppo2.Echo_Ingressi[7]',  'db200_dbx118_6', 'bool', '"PX2403 Transfer Rallentamento Inferiore (E8.3)'),
	('Status.Gruppo2.Echo_Ingressi[8]',  'db200_dbx118_7', 'bool', '"PX2404 Transfer Rallentamento Superiore (E8.4)'),
	('Status.Gruppo2.Echo_Ingressi[9]',  'db200_dxb119_0', 'bool', '"PX2405 Transfer in posizione Superiore (E8.5)'),
	('Status.Gruppo2.Echo_Ingressi[10]', 'db200_dxb119_1', 'bool', '"SQ2407 Bloccaggio Transfer Sbloccato (E8.7)'),
	('Status.Gruppo2.Echo_Ingressi[11]', 'db200_dxb119_2', 'bool', '"SQ2406 Bloccaggio Transfer Bloccato (E8.6)'),
	('Status.Gruppo2.Echo_Ingressi[12]', 'db200_dxb119_3', 'bool', '"PX2502 Tavolo Formatrice in emergenza (E9.2)'),
	('Status.Gruppo2.Echo_Ingressi[13]', 'db200_dxb119_4', 'bool', '"PX2501 Tavolo Formatrice in Carico Terra (E9.1)'),
	('Status.Gruppo2.Echo_Ingressi[14]', 'db200_dxb119_5', 'bool', '"PX2503 Tavolo Formatrice in Rallentamento di Sformatura (E9.3)'),
	('Status.Gruppo2.Echo_Ingressi[15]', 'db200_dxb119_6', 'bool', '"PX2500 Tavolo Formatrice Basso (E9.0)'),
	('Status.Gruppo2.Echo_Ingressi[16]', 'db200_dxb119_7', 'bool', '"PX2600 Tramoggia Terra Formatrice Aperta (E10.0)'),
	('Status.Gruppo2.Echo_Ingressi[17]', 'db200_dbx120_0', 'bool', '"PX2601 Tramoggia Terra Formatrice Rallentamento Aperta (E10.1)'),
	('Status.Gruppo2.Echo_Ingressi[18]', 'db200_dbx120_1', 'bool', '"PX2602 Tramoggia Terra Formatrice Rallentamento Chiusa (E10.2)'),
	('Status.Gruppo2.Echo_Ingressi[19]', 'db200_dbx120_2', 'bool', '"PX2603 Tramoggia Terra Formatrice Chiusa (E10.3)'),
	('Status.Gruppo2.Echo_Ingressi[20]', 'db200_dbx120_3', 'bool', '"PX1607 Presenza Terra su estrattore Carica Formatrice (E0.7)'),
	('Status.Gruppo2.Echo_Ingressi[21]', 'db200_dbx120_4', 'bool', '"M5.1 Memoria Stop Pressata Superiore'),
	('Status.Gruppo2.Echo_Ingressi[22]', 'db200_dbx120_5', 'bool', '"M5.2 Memoria Stop Pressata Inferiore'),
	('Status.Gruppo2.Echo_Ingressi[23]', 'db200_dbx120_6', 'bool', '"PX2200 Ribaltatore Tutte Posizione 1 (E6.0)'),
	('Status.Gruppo2.Echo_Ingressi[24]', 'db200_dbx120_7', 'bool', '"PX2201  Ribaltatore Tutte Posizione 2 (E6.1)'),
	('Status.Gruppo2.Echo_Ingressi[25]', 'db200_dbx121_0', 'bool', '"PX2202 Ribaltatore Tutte Posizione Centrale (E6.2)'),
	('Status.Gruppo2.Echo_Ingressi[26]', 'db200_dbx121_1', 'bool', '"PX2106 Fresa Staffe Alta (E5.6)'),
	('Status.Gruppo2.Echo_Ingressi[27]', 'db200_dbx121_2', 'bool', '"PX2107 Fresa Staffe Bassa (E5.7)'),
	('Status.Gruppo2.Echo_Ingressi[28]', 'db200_dbx121_3', 'bool', '"SQ2011 Bloccaggio su ribaltatore 1/2 superiore sbloccato (E4.1)'),
	('Status.Gruppo2.Echo_Ingressi[29]', 'db200_dbx121_4', 'bool', '"SQ2010 Bloccaggio su ribaltatore 1/2 superiore bloccato (E4.0)'),
]

VARS_GRUPPO_2_ALLARMI = [
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_0', 'bool', 'Timeout Gruppo 2 - Blocca Bloccaggio Transfer - controllare SQ2306 (Bloccaggio Prima della Formatrice Bloccato)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_1', 'bool', 'Timeout Gruppo 2 - Salita Terra in carico Pressa- controllare PX2501 (Tavolo Formatrice in Carico Terra) '),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_2', 'bool', 'Timeout Gruppo 2 - Stop presa in carico Terra - controllare Tempo Manuale Estrattore Terra DM'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_3', 'bool', 'Timeout Gruppo 2 - Stop presa in carico Terra - controllare Caricamento Terra non valido (T65)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_4', 'bool', 'Timeout Gruppo 2 - Stop presa in carico Terra - controllare KM4506 (Estrattore Terra in Formatrice)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_5', 'bool', 'Timeout Gruppo 2 - Apertura Tramoggia Terra - controllare PX2600 e PX2603 (Tramoggia Terra formatrice Aperta / Chiusa)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_6', 'bool', 'Timeout Gruppo 2 - Chiusura Tramoggia Terra - controllare PX2603 (Tramoggia Terra Formatrice Chiusa)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx122_7', 'bool', 'Timeout Gruppo 2 - Pressata 1/2 Superiore - Controllare memoria pressata Eseguita'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_0', 'bool', 'Timeout Gruppo 2 - Sblocca Bloccaggi Linea Ramolaggio - controllare fase Bloccaggi Linea ramolaggio)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_1', 'bool', 'Timeout Gruppo 2 - Sblocca Bloccaggi Linea Ramolaggio - controllare SQ2307 (Bloccaggio prima della Formatrice Sbloccato) '),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_2', 'bool', 'Timeout Gruppo 2 - Uscita Spintore Ramolaggio - controllare PX2400 (Spintore Formatrice Fuori)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_3', 'bool', 'Timeout Gruppo 2 - Blocca Bloccaggi Linea Ramolaggio - controllare SQ2307 (Bloccaggio Prima della formatrice sbloccato)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_4', 'bool', 'Timeout Gruppo 2 - Entrata Spintore Ramolaggio - controllare PX2401 (Spintore Formatrice Dentro)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_5', 'bool', 'Timeout Gruppo 2 - Sblocca Bloccaggio Transfer - controllare SQ2407 (Bloccaggio Transfer Sbloccato)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_6', 'bool', 'Timeout Gruppo 2 - Sblocca Bloccaggio Transfer - controllare PX2405 (Transfer in posizione Superiore)'),
	('Status.Gruppo2.Timeout[1]', 'db200_dbx123_7', 'bool', 'Timeout Gruppo 2 - Blocca Bloccaggio Transfer - controllare SQ2406 (Bloccaggio Transfer Bloccato)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_0', 'bool', 'Timeout Gruppo 2 - Esce Spintore Ramolaggio *II - controllare PX2400 (Spintore Formatrice Fuori) '),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_1', 'bool', 'Timeout Gruppo 2 - Blocca Bloccaggi Linea Ramolaggio - controllare SQ2307 (bloccaggio prima della formatrice sbloccato)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_2', 'bool', 'Timeout Gruppo 2 - Entra Spintore ramolaggio *II - controllare PX2401 (Spintore Formatrice Dentro)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_3', 'bool', 'Timeout Gruppo 2 - Sblocca bloccaggio Transfer *II - controllare SQ2407 (Bloccaggio transfer Sbloccato)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_4', 'bool', 'Timeout Gruppo 2 - Sblocca bloccaggio Transfer *II - controllare  PX2402 (Transfer in posizione Inferiore)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_5', 'bool', 'Timeout Gruppo 2 - Blocca Bloccaggio Transfer *II - controllare SQ2406 (Bloccaggio Transfer Bloccato)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_6', 'bool', 'Timeout Gruppo 2 - Blocca Bloccaggio Transfer *II - controllare SQ2306 (Bloccaggio prima della formatrice bloccato)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx124_7', 'bool', 'Timeout Gruppo 2 - Salita Pressa in Carico Terra *II - controllare PX2501 (Tavolo Formatrice in Carico Terra)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_0', 'bool', 'Timeout Gruppo 2 - Discesa Pressa - controllare PX2500 (Tavolo Formatrice Basso)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_1', 'bool', 'Timeout Gruppo 2 - Start Ribaltatore Tutte - controllare ribaltamento eseguito'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_2', 'bool', 'Timeout Gruppo 2 - Ribaltamento Tutte Manovra Eseguita - controllare Pressa Bassa (Memoria) '),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_3', 'bool', 'Timeout Gruppo 2 - Ribaltamento Tutte Manovra Eseguita - controllare Sblocco staffa sotto disaccoppiatore (Memoria) '),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_4', 'bool', 'Timeout Gruppo 2 - Ribaltamento Tutte Manovra Eseguita - controllare posizione pressa '),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_5', 'bool', 'Timeout Gruppo 2 - Sblocca Bloccaggio Linea Ramolaggio - controllare SQ2307 (Bloccaggio Prima della formatrice sbloccato)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_6', 'bool', 'Timeout Gruppo 2 - Sblocca Bloccaggio Linea Ramolaggio - controllare Consenso per seconda spinta (Memoria)'),
	('Status.Gruppo2.Timeout[2]', 'db200_dbx125_7', 'bool', 'Timeout Gruppo 2 - Sblocca Bloccaggio Linea Ramolaggio - controllare posizione pressa'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_0', 'bool', 'Timeout Gruppo 2 - Salita Fresa Foro Colata - controllare PX2106 (Fresa stafdfe Alta)'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_1', 'bool', 'Timeout Gruppo 2 - Discesa Fresa Foro Colata e fine ciclo - controllare Ribaltamento Eseguito (Memoria)  '),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_2', 'bool', 'Timeout Gruppo 2 - Discesa Fresa Foro Colata e fine ciclo - controllare PX2107 (Fresa Staffe Bassa)  '),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_3', 'bool', 'Timeout Gruppo 2 - Discesa Fresa Foro Colata e fine ciclo - controllare Bassa Pressione (Memoria) '),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_4', 'bool', 'Timeout Gruppo 2 - Discesa Fresa Foro Colata e fine ciclo - controllare Spintore Ramolaggio Dentro (Memoria) '),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_5', 'bool', 'Gruppo 2 - Anomalia Sensori  SQ2307/SQ2306 Bloccaggio Prima della Formqatrice'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_6', 'bool', 'Gruppo 2 - Anomalia Sensori  PX2400/PX2401 Spintore Formatrice'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx126_7', 'bool', 'Gruppo 2 - Anomalia Sensori PX2402/PX2405 Transfer Superiore/Inferiore'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_0', 'bool', 'Timeout Gruppo 2 - Stop Pressa in Carico Terra *II - controllare KM4506 (Estrattore Terra in Formatrice)'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_1', 'bool', 'Timeout Gruppo 2 - Stop Pressa in Carico Terra *II - controllare Tempo manuale estrattore Terra DM'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_2', 'bool', 'Timeout Gruppo 2 - Stop Pressa in Carico Terra *II - controllare Caricamento Terra non Valido (T65) '),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_3', 'bool', 'Timeout Gruppo 2 - Apertura Tramoggia Terra *II - controllare PX2600 e PX2603 (Tramoggia Terra formatrice Aperta / Chiusa)'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_4', 'bool', 'Timeout Gruppo 2 - Chiusura Tramoggia Terra *II - controllare  PX2603 (Tramoggia Terra Formatrice Chiusa)  '),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_5', 'bool', 'Timeout Gruppo 2 - Pressata 1/2 Superiore *II - controllare memoria pressata Eseguita '),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_6', 'bool', 'Timeout Gruppo 2 - Discesa Pressa *II - controllare PX2500 (Tavolo Formatrice Basso)'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx127_7', 'bool', 'Timeout Gruppo 2 - Start Ribaltatore Tutte *II - controllare ribaltamento eseguito'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_0', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_1', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_2', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_3', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_4', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_5', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_6', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[3]', 'db200_dbx128_7', 'bool', 'NONE'),
	('Status.Gruppo2.Timeout[4]', 'db200_dbx129_0', 'bool', 'Gruppo 2 - Anomalia Sensori  PX2600/PX2603 Tramoggia Terra Formatrice Aperta/Chiusa'),
	('Status.Gruppo2.Timeout[4]', 'db200_dbx129_1', 'bool', 'Gruppo 2 - Anomalia Sensori PX2200/PX2201/PX2202 Ribaltatore Tutte'),
	('Status.Gruppo2.Timeout[4]', 'db200_dbx129_2', 'bool', 'Gruppo 2 - Anomalia Sensori PX2106/PX2107 Fresa Staffe Alta/Bassa'),
	('Status.Gruppo2.Timeout[4]', 'db200_dbx129_3', 'bool', 'Gruppo 2 - Anomalia Sensori SQ2010/SQ2011 Bloccaggio su ribaltatore 1/2 superiore'),
]




VARS_GRUPPO_3_FASI = [
	('Status.Gruppo3.Passo_Auto_Sequenza[1]',  'db200_dbx170_0', 'bool', 'Fase Spinge Traino Giostra Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[2]',  'db200_dbx170_1', 'bool', 'Fase  Abbassa Impegno Giostra Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[3]',  'db200_dbx170_2', 'bool', 'Fase  Traino Giostra Indietro (carico) Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[4]',  'db200_dbx170_3', 'bool', 'Fase  Alza Impegno Giostra Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[5]',  'db200_dbx170_4', 'bool', 'Fase  Spazzola Pulizia Pianette Avanti Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[6]',  'db200_dbx170_5', 'bool', 'Fase  Spazzola Pulizia Pianette indietro Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[7]',  'db200_dbx170_6', 'bool', 'Fase  Uscita Contrasto Ramolaggio Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[8]',  'db200_dbx170_7', 'bool', 'Fase  Sblocca Bloccaggi Ribaltatore 1/2 superiore Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[9]',  'db200_dbx171_0', 'bool', 'Fase  Consenso per prima spinta da gruppo P3 Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[10]', 'db200_dbx171_1', 'bool', 'Fase  Rientro Contrasto Ramolaggio Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[11]', 'db200_dbx171_2', 'bool', 'Fase  Blocca Ribaltamento 1/2 Superiore Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[12]', 'db200_dbx171_3', 'bool', 'Fase  Start Ribaltatore 1/2 superiore Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[13]', 'db200_dbx171_4', 'bool', 'Fase  Abbassa Spina di Accoppiamento Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[14]', 'db200_dbx171_5', 'bool', 'Fase  Accoppiatore Deposita 1/2 inferiore Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[15]', 'db200_dbx171_6', 'bool', 'Fase  Apertura Pinza Accoppiatore Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[16]', 'db200_dbx171_7', 'bool', 'Fase  Alza Spina di Accoppiamento Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[17]', 'db200_dbx172_0', 'bool', 'Fase  Salita Accoppiatore Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[18]', 'db200_dbx172_1', 'bool', 'Fase  Chiusura pinza Accoppiatore Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[19]', 'db200_dbx172_2', 'bool', 'Fase  Uscita Contarsto Ramolaggio *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[20]', 'db200_dbx172_3', 'bool', 'Fase  Ribaltatore 1/2 Superiore Manovra Eseguita Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[21]', 'db200_dbx172_4', 'bool', 'Fase  Sblocca Bloccaggio Ribaltatore 1/2 Superiore *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[22]', 'db200_dbx172_5', 'bool', 'Fase  Consenso per seconda spinta da gruppo P3 Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[23]', 'db200_dbx172_6', 'bool', 'Fase  rientro Contrasto ramolaggio Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[24]', 'db200_dbx172_7', 'bool', 'Fase  Blocca Bloccaggio Ribaltatore 1/2 Superiore *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[25]', 'db200_dbx173_0', 'bool', 'Fase  Abbassa Spina di Accoppiamento *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[26]', 'db200_dbx173_1', 'bool', 'Fase  Accoppiatore Deposita 1/2 inferiore *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[27]', 'db200_dbx173_2', 'bool', 'Fase  Apertura Pinza Accoppaitore *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[28]', 'db200_dbx173_3', 'bool', 'Fase  Alza Spina accoppiamento *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[29]', 'db200_dbx173_4', 'bool', 'Fase  Salita Accoppiatore *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[30]', 'db200_dbx173_5', 'bool', 'Fase  Chiusura Pinza Accoppiatore *II Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[31]', 'db200_dbx173_6', 'bool', 'Fase  Traslazione pesi --> prelievo Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[32]', 'db200_dbx173_7', 'bool', 'Fase  Salita Sollevatore Pesi Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[33]', 'db200_dbx174_0', 'bool', 'Fase  Traslazione pesi --> Deposito Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[34]', 'db200_dbx174_1', 'bool', 'Fase  Discesa Sollevatore Pesi Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[35]', 'db200_dbx174_2', 'bool', 'Fase  Traslazione Pesi --> Pos. Intermedia Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[36]', 'db200_dbx174_3', 'bool', 'Fase  Fine Ciclo Cambio Pesi Attiva'),
	('Status.Gruppo3.Passo_Auto_Sequenza[37]', 'db200_dbx174_4', 'bool', 'Fase  Fine Ciclo Gruppo 3 Attiva'),
]

VARS_GRUPPO_3_INGRESSI = [
	('Status.Gruppo3.Echo_Ingressi[1]',  'db200_dbx182_0', 'bool', 'PX2203 Ribaltatore 1/2 Superiore posizione 1 (E6.3)'),
	('Status.Gruppo3.Echo_Ingressi[2]',  'db200_dbx182_1', 'bool', 'PX2205 Ribaltatore 1/2 Superiore posizione centrale (E6.5)'),
	('Status.Gruppo3.Echo_Ingressi[3]',  'db200_dbx182_2', 'bool', 'PX2204 Ribaltatore 1/2 Superiore posizione 2 (E6.4)'),
	('Status.Gruppo3.Echo_Ingressi[4]',  'db200_dbx182_3', 'bool', 'SQ2002 Pinza Accoppiatore Aperta (E4.2)'),
	('Status.Gruppo3.Echo_Ingressi[5]',  'db200_dbx182_4', 'bool', 'SQ2003 Pinza Accoppiatore Chiusa (E4.3)'),
	('Status.Gruppo3.Echo_Ingressi[6]',  'db200_dbx182_5', 'bool', 'PX2100 Accoppiatore Staffe Basso deposito 1/2 inferiore (E5.0)'),
	('Status.Gruppo3.Echo_Ingressi[7]',  'db200_dbx182_6', 'bool', 'PX2007 Accoppiatore Staffe Rallentamento Basso  deposito 1/2 inferiore (E4.7)'),
	('Status.Gruppo3.Echo_Ingressi[8]',  'db200_dbx182_7', 'bool', 'PX2006 Accoppiatore Staffe 1/2 Superiore (E4.6)'),
	('Status.Gruppo3.Echo_Ingressi[9]',  'db200_dbx183_0', 'bool', 'PX2005 Accoppiatore Staffe Rallentamento Deposito 1/2 Superiore  (E4.5)'),
	('Status.Gruppo3.Echo_Ingressi[10]', 'db200_dbx183_1', 'bool', 'PX2004 Accoppiatore Staffe Alto (E4.4)'),
	('Status.Gruppo3.Echo_Ingressi[11]', 'db200_dbx183_2', 'bool', 'PX2104 Spine di Accoppiamento Fuori (E5.4)'),
	('Status.Gruppo3.Echo_Ingressi[12]', 'db200_dbx183_3', 'bool', 'PX2105 Spine di Accoppiamento Dentro (E5.5)'),
	('Status.Gruppo3.Echo_Ingressi[13]', 'db200_dbx183_4', 'bool', 'PX2101 Contrasto Ramolaggio Fuori (E5.1)'),
	('Status.Gruppo3.Echo_Ingressi[14]', 'db200_dbx183_5', 'bool', 'PX2102 Contrasto Ramolaggio Dentro (E5.2)'),
	('Status.Gruppo3.Echo_Ingressi[15]', 'db200_dbx183_6', 'bool', 'PX2206 Traslatore Pesi su linea Deposito (E6.6)'),
	('Status.Gruppo3.Echo_Ingressi[16]', 'db200_dbx183_7', 'bool', 'PX2207 Traslatore Pesi Rallentamento verso deposito (E6.7)'),
	('Status.Gruppo3.Echo_Ingressi[17]', 'db200_dbx184_0', 'bool', 'PX2300 Traslatore Pesi Rallentamento Intermedio (E7.0)'),
	('Status.Gruppo3.Echo_Ingressi[18]', 'db200_dbx184_1', 'bool', 'PX2301 Traslatore Pesi in posizione Intermedia (E7.1)'),
	('Status.Gruppo3.Echo_Ingressi[19]', 'db200_dbx184_2', 'bool', 'PX2302 Traslatore Pesi Rallentamento Linea Prelievo (E7.2)'),
	('Status.Gruppo3.Echo_Ingressi[20]', 'db200_dbx184_3', 'bool', 'PX2304 Traslatore Pesi in Posizione Prelievo (E7.3)'),
	('Status.Gruppo3.Echo_Ingressi[21]', 'db200_dbx184_4', 'bool', 'SQ2304 Sollevatore Pesi Alto (E7.4)'),
	('Status.Gruppo3.Echo_Ingressi[22]', 'db200_dbx184_5', 'bool', 'SQ2305 Sollevatore Pesi Basso (E7.5)'),
	('Status.Gruppo3.Echo_Ingressi[23]', 'db200_dbx184_6', 'bool', 'PX1601 Impegno Traino basso (E0.1)'),
	('Status.Gruppo3.Echo_Ingressi[24]', 'db200_dbx184_7', 'bool', 'PX1600 Impegno Traino Alto (E0.0)'),
	('Status.Gruppo3.Echo_Ingressi[25]', 'db200_dbx185_0', 'bool', 'PX1602 Spintore Traino Fine Spinta (E0.2)'),
	('Status.Gruppo3.Echo_Ingressi[26]', 'db200_dbx185_1', 'bool', 'PX1604 Spintore Traino Rallentamento (E0.4)'),
	('Status.Gruppo3.Echo_Ingressi[27]', 'db200_dbx185_2', 'bool', 'PX1603 Spintore Traino Carico (E0.3)'),
	('Status.Gruppo3.Echo_Ingressi[28]', 'db200_dbx185_3', 'bool', 'PX1605 Pulisci Pianette Fuori (E0.5)'),
	('Status.Gruppo3.Echo_Ingressi[29]', 'db200_dbx185_4', 'bool', 'PX1606 Pulisci Pianette Dentro (E0.6)'),
]

VARS_GRUPPO_3_ALLARMI = [
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_0', 'bool', 'Timeout Gruppo 3 - Rientro Contrasto Ramolaggio - controllare PX2102 (Contrasto ramolaggio Dentro)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_1', 'bool', 'Timeout Gruppo 3 - Blocca Ribaltamento 1/2 Superiore - controllare SQ2010 (Bloccaggio su ribaltatore 1/2 superiore bloccato)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_2', 'bool', 'Timeout Gruppo 3 - Start Ribaltatore 1/2 superiore - controllare Ribaltamento Eseguito (Memoria)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_3', 'bool', 'Timeout Gruppo 3 - Abbassa Spina di Accoppiamento - controllare PX2104 (Spine di Accoppiamento Fuori)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_4', 'bool', 'Timeout Gruppo 3 - Abbassa Spina di Accoppiamento - controllare Memoria Abbassa impegno Giostra'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_5', 'bool', 'Timeout Gruppo 3 - Accoppiatore Deposita 1/2 inferiore - controllare PX2100 (Accoppiatore Basso)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_6', 'bool', 'Timeout Gruppo 3 - Apertura Pinza Accoppiatore - controllare SQ2002 (Pinza Accoppiatore Aperta)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx186_7', 'bool', 'Timeout Gruppo 3 - Salita Accoppiatore - controllare PX2004 (Accoppiatore Staffe Alto)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_0', 'bool', 'Timeout Gruppo 3 - Spinge Traino Giostra - controllare PX1602 (Spintore Traino Fine Spinta)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_1', 'bool', 'Timeout Gruppo 3 - Abbassa Impegno Giostra - controllare PX1601 (Impegno Traino Basso)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_2', 'bool', 'Timeout Gruppo 3 - Traino Giostra Indietro (carico) - controllare PX1603 (Spintore Traino Carico)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_3', 'bool', 'Timeout Gruppo 3 - Alza Impegno Giostra - controllare PX1600 (Impegno traino Alto)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_4', 'bool', 'Timeout Gruppo 3 - Spazzola Pulizia Pianette Avanti - controllare PX1605 (Pulisci Pianette Fuori)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_5', 'bool', 'Timeout Gruppo 3 - Spazzola Pulizia Pianette indietro - controllare PX1606 (Pulisci Pianette Dentro)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_6', 'bool', 'Timeout Gruppo 3 - Uscita Contrasto Ramolaggio - controllare PX2011 (Bloccaggio su ribaltatore 1/2 superiore bloccato)'),
	('Status.Gruppo3.Timeout[1]', 'db200_dbx187_7', 'bool', 'Timeout Gruppo 3 - Uscita Contrasto Ramolaggio - controllare PX2101 (Contrasto Ramolaggio Fuori)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_0', 'bool', 'Timeout Gruppo 3 - Accoppiatore Deposita 1/2 inferiore *II - controllare PX2006 (Accoppiatore Staffe deposito 1/2 Superiore)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_1', 'bool', 'Timeout Gruppo 3 - Apertura Pinza Accoppaitore *II - controllare SQ2002 (Pinza Acoppiatore Aperta)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_2', 'bool', 'Timeout Gruppo 3 - Alza Spina accoppiamento *II - controllare PX2105 (Spine di Accoppiamento Dentro)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_3', 'bool', 'Timeout Gruppo 3 - Salita Accoppiatore *II - controllare PX2004 (Accoppiatore Staffe Alte)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_4', 'bool', 'Timeout Gruppo 3 - Traslazione pesi --> prelievo - controllare PX2304 (Traslatore Pesi in posizione linea prelievo)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_5', 'bool', 'Timeout Gruppo 3 - Salita Sollevatore Pesi - controllare SQ2304 (Sollevatore Pesi Alto)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_6', 'bool', 'Timeout Gruppo 3 - Traslazione pesi --> Deposito - controllare PX2206 (Traslatore Pesi su linea Deposito) '),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx188_7', 'bool', 'Timeout Gruppo 3 - Discesa Sollevatore Pesi - controllare SQ2305 (Sollevatore Pesi Basso)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_0', 'bool', 'Timeout Gruppo 3 - Chiusura pinza Accoppiatore - controllare PC2105 (Spine di Accoppiamento Dentro)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_1', 'bool', 'Timeout Gruppo 3 - Chiusura pinza Accoppiatore - controllare SQ2003 (Pinza Accoppiatore Chiusa)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_2', 'bool', 'Timeout Gruppo 3 - Uscita Contarsto Ramolaggio *II - controllare SQ2003 (Pinza Accoppiatore Chiusa)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_3', 'bool', 'Timeout Gruppo 3 - Sblocca Bloccaggio Ribaltatore 1/2 Superiore *II - controllare SQ2011 (Bloccaggio su ribaltatore 1/2 superiore bloccato)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_4', 'bool', 'Timeout Gruppo 3 - Sblocca Bloccaggio Ribaltatore 1/2 Superiore *II - controllare PX2101 (Contrasto Ramolaggio Fuori)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_5', 'bool', 'Timeout Gruppo 3 - Rientro Contrasto ramolaggio - controllare PX2102 (Contrasto ramolaggio Dentro)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_6', 'bool', 'Timeout Gruppo 3 - Rientro Contrasto ramolaggio - controllare SQ2010 (Bloccaggio su ribaltatore 1/2 superiore bloccato)'),
	('Status.Gruppo3.Timeout[2]', 'db200_dbx189_7', 'bool', 'Timeout Gruppo 3 - Abbassa Spina di Accoppiamento *II - controllare PX2104 (Spine di Accoppiamento Fuori)'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_0', 'bool', 'Gruppo 3 Anomalia Sensori - PX1601/PX1600 Impegno Traino'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_1', 'bool', 'Gruppo 3 Anomalia Sensori - PX1602/PX1603 Spintore Traino'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_2', 'bool', 'Gruppo 3 Anomalia Sensori - PX1605/PX1606'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_3', 'bool', 'NONE'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_4', 'bool', 'NONE'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_5', 'bool', 'NONE'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_6', 'bool', 'NONE'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx190_7', 'bool', 'NONE'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_0', 'bool', 'Timeout Gruppo 3 - Traslazione Pesi --> Pos. Intermedia - controllare PX2301 (Traslatore Pesi in posizione intermedia)'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_1', 'bool', 'Gruppo 3 Anomalia Sensori -PX2203/PX2204/PX2205 Ribaltatore 1/2 Superiore'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_2', 'bool', 'Gruppo 3 Anomalia Sensori - SQ2002/SQ2003 Pinza Accoppiatore'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_3', 'bool', 'Gruppo 3 Anomalia Sensori - PX2100/PX2006/PX2004 Accoppiatore Basso/Alto'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_4', 'bool', 'Gruppo 3 Anomalia Sensori - PX2104/PX2105 Spine di Accoppiamento'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_5', 'bool', 'Gruppo 3 Anomalia Sensori - PX2101/PX2102 Contrasto Ramolaggio'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_6', 'bool', 'Gruppo 3 Anomalia Sensori - PX2206/PX2301/PX2304 Traslatore Pesi'),
	('Status.Gruppo3.Timeout[3]', 'db200_dbx191_7', 'bool', 'Gruppo 3 Anomalia Sensori - SQ2304/SQ2305 Sollevatore Pesi'),
]


Gruppo1 = [VARS_GRUPPO_1_FASI, VARS_GRUPPO_1_INGRESSI, VARS_GRUPPO_1_ALLARMI]
Gruppo2 = [VARS_GRUPPO_2_FASI, VARS_GRUPPO_2_INGRESSI, VARS_GRUPPO_2_ALLARMI]
Gruppo3 = [VARS_GRUPPO_3_FASI, VARS_GRUPPO_3_INGRESSI, VARS_GRUPPO_3_ALLARMI]

Generale = VARS_GENERALE

#Labels = [Generale, Gruppo1, Gruppo2, Gruppo3]

class Labels:
    Generale = VARS_GENERALE

    class Gruppo1:
        Fasi = VARS_GRUPPO_1_FASI
        Ingressi = VARS_GRUPPO_1_INGRESSI
        Allarmi = VARS_GRUPPO_1_ALLARMI

    class Gruppo2:
        Fasi = VARS_GRUPPO_2_FASI
        Ingressi = VARS_GRUPPO_2_INGRESSI
        Allarmi = VARS_GRUPPO_2_ALLARMI

    class Gruppo3:
        Fasi = VARS_GRUPPO_3_FASI
        Ingressi = VARS_GRUPPO_3_INGRESSI
        Allarmi = VARS_GRUPPO_3_ALLARMI
