version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
    - 1883:1883
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - 27018:27017