# TODO: non so a che cazzo serve a ora per se la cancello git impazzisce e non me la sento

LABEL_CC_BATTS_V           = "battsV"
LABEL_CC_BATT_SENSED_V     = "battsSensedV"
LABEL_CC_BATTS_I           = "battsI"
LABEL_CC_ARRAY_V           = "arrayV"
LABEL_CC_ARRAY_I           = "arrayI"
LABEL_CC_STATENUM          = "statenum"
LABEL_CC_HS_TEMP           = "hsTemp"
LABEL_CC_RTS_TEMP          = "rtsTemp"
LABEL_CC_OUT_POWER         = "outPower"
LABEL_CC_IN_POWER          = "inPower"
LABEL_CC_MINVB_DAILY       = "minVb_daily"
LABEL_CC_MAXVB_DAILY       = "maxVb_daily"
LABEL_CC_MINTB_DAILY       = "minTb_daily"
LABEL_CC_MAXTB_DAILY       = "maxTb_daily"
LABEL_CC_DIPSWITCHES       = "dipswitches"

LABEL_RB_VB                = "adc_vb"
LABEL_RB_ADC_VCH_1         = "adc_vch_1"
LABEL_RB_ADC_VCH_2         = "adc_vch_2"
LABEL_RB_ADC_VCH_3         = "adc_vch_3"
LABEL_RB_ADC_VCH_4         = "adc_vch_4"
LABEL_RB_T_MOD             = "t_mod"
LABEL_RB_GLOBAL_FAULTS     = "global_faults"
LABEL_RB_GLOBAL_ALARMS     = "global_alarms"
LABEL_RB_HOURMETER_HI      = "hourmeter_HI"
LABEL_RB_HOURMETER_LO      = "hourmeter_LO"
LABEL_RB_CH_FAULTS_1       = "ch_faults_1"
LABEL_RB_CH_FAULTS_2       = "ch_faults_2"
LABEL_RB_CH_FAULTS_3       = "ch_faults_3"
LABEL_RB_CH_FAULTS_4       = "ch_faults_4"
LABEL_RB_CH_ALARMS_1       = "ch_alarms_1"
LABEL_RB_CH_ALARMS_2       = "ch_alarms_2"
LABEL_RB_CH_ALARMS_3       = "ch_alarms_3"
LABEL_RB_CH_ALARMS_4       = "ch_alarms_4"

LABEL_RS_RELAY_1           = "relay_1"
LABEL_RS_RELAY_2           = "relay_2"
LABEL_RS_RELAY_3           = "relay_3"
LABEL_RS_RELAY_4           = "relay_4"
LABEL_RS_RELAY_5           = "relay_5"
LABEL_RS_RELAY_6           = "relay_6"
LABEL_RS_RELAY_7           = "relay_7"
LABEL_RS_RELAY_8           = "relay_8"

LABEL_MCU_TEMP_1           =  'temp1' # DS18D20 ( onewire, D5 )
LABEL_MCU_TEMP_2           =  'temp2' # DS18D20 ( onewire, D5 )
LABEL_MCU_TEMP_3           =  'temp3' # DS18D20 ( onewire, D5 )
LABEL_MCU_PRESSURE_IN      =  'pres1' # PRESSURE (analog, A1)
LABEL_MCU_PRESSURE_OUT     =  'pres2' # PRESSURE (analog, A2)
LABEL_MCU_PRESSURE_MIDDLE  =  'pres3' # PRESSURE (analog, A3)
LABEL_MCU_FLUX_IN          =  'flux1' # FLUXMETER ( digital input, D2 )
LABEL_MCU_FLUX_OUT         =  'flux2' # FLUXMETER ( digital input, D3 )
LABEL_MCU_CC_CURRENT       =  'cc' # SHUNT  ( LM358 gain 20, analog, A0  )
LABEL_MCU_AC1_CURRENT      =  'ac1' # SCT013 (analog in A5)
LABEL_MCU_AC2_CURRENT      =  'ac2' # SCT013 (analog in A5)
LABEL_MCU_DHT11_AIR        =  'dht_temp'# DHT11 ( onewire, D6 )
LABEL_MCU_DHT11_HUMIDITY   =  'dht_hum' # DHT11 ( onewire, D6 )
LABEL_MCU_FLOODING_STATUS  =  'flood' # Flooding sensor ( digital input, D7 )
LABEL_MCU_WATER_LEVEL      =  'water_lev' # DISTANCE ULTRASOUND SENSOR ( software serial,
